import type { Metadata } from "next";
import { Inter, Itim } from "next/font/google";
import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter"
 });

const itim = Itim({
  weight: "400",
  variable: "--font-itim",
  subsets: ["latin", "thai"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${itim.variable}`}>
          {children}
      </body>
    </html>
  );
}
